installs:
  swap_space: n
  nginx: yes
  php:
    install: yes
    composer: yes
    php_version: 8.3   # version (e.g., 8.3)
  node_and_npm: yes
  redis: yes
  sqlite: yes
  database:
    mysql: yes
    mariadb: yes
    db_root_password: secret
  certbot: yes
  apache: yes
  memcache: yes
  beanstalk: yes
  mailhog: yes
  ngrok: yes
  postfix: yes



