installs:
  swap_space: n
  nginx: yes
  php:
    install: yes
    composer: yes
    version: 8.3   # version (e.g., 8.3)
  node_and_npm: yes
  redis: yes
  sqlite: yes
  database:
    mysql: yes
    mariadb: no
    db_root_password: secret
  certbot: yes
  apache: no
  memcache: no
  beanstalk: no
  mailhog: no
  ngrok: no
  postfix: no



